# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 567)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(290, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("")
        self.TitleLabel.setObjectName("TitleLabel")
        self.ChooseFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseFileBtn.setGeometry(QtCore.QRect(470, 40, 81, 31))
        self.ChooseFileBtn.setObjectName("ChooseFileBtn")
        self.FileNameText = QtWidgets.QLineEdit(self.centralwidget)
        self.FileNameText.setGeometry(QtCore.QRect(230, 40, 241, 31))
        self.FileNameText.setObjectName("FileNameText")
        self.Picture = QtWidgets.QGraphicsView(self.centralwidget)
        self.Picture.setGeometry(QtCore.QRect(20, 230, 391, 241))
        self.Picture.setObjectName("Picture")
        self.ResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.ResultLabel.setGeometry(QtCore.QRect(560, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ResultLabel.setFont(font)
        self.ResultLabel.setObjectName("ResultLabel")
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel.setGeometry(QtCore.QRect(460, 280, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.NameText = QtWidgets.QLineEdit(self.centralwidget)
        self.NameText.setGeometry(QtCore.QRect(510, 280, 211, 21))
        self.NameText.setObjectName("NameText")
        self.SexLabel = QtWidgets.QLabel(self.centralwidget)
        self.SexLabel.setGeometry(QtCore.QRect(460, 320, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SexLabel.setFont(font)
        self.SexLabel.setObjectName("SexLabel")
        self.SexText = QtWidgets.QLineEdit(self.centralwidget)
        self.SexText.setGeometry(QtCore.QRect(510, 320, 211, 21))
        self.SexText.setObjectName("SexText")
        self.NationLabel = QtWidgets.QLabel(self.centralwidget)
        self.NationLabel.setGeometry(QtCore.QRect(460, 360, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NationLabel.setFont(font)
        self.NationLabel.setObjectName("NationLabel")
        self.NationText = QtWidgets.QLineEdit(self.centralwidget)
        self.NationText.setGeometry(QtCore.QRect(510, 360, 211, 21))
        self.NationText.setObjectName("NationText")
        self.NumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.NumberLabel.setGeometry(QtCore.QRect(440, 400, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NumberLabel.setFont(font)
        self.NumberLabel.setObjectName("NumberLabel")
        self.NumberText = QtWidgets.QLineEdit(self.centralwidget)
        self.NumberText.setGeometry(QtCore.QRect(510, 400, 211, 21))
        self.NumberText.setObjectName("NumberText")
        self.AddressLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddressLabel.setGeometry(QtCore.QRect(220, 100, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AddressLabel.setFont(font)
        self.AddressLabel.setObjectName("AddressLabel")
        self.LineVerticalLeft = QtWidgets.QFrame(self.centralwidget)
        self.LineVerticalLeft.setGeometry(QtCore.QRect(190, 90, 16, 121))
        self.LineVerticalLeft.setFrameShape(QtWidgets.QFrame.VLine)
        self.LineVerticalLeft.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineVerticalLeft.setObjectName("LineVerticalLeft")
        self.LineHorizontalDown = QtWidgets.QFrame(self.centralwidget)
        self.LineHorizontalDown.setGeometry(QtCore.QRect(200, 190, 351, 41))
        self.LineHorizontalDown.setAutoFillBackground(False)
        self.LineHorizontalDown.setFrameShape(QtWidgets.QFrame.HLine)
        self.LineHorizontalDown.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineHorizontalDown.setObjectName("LineHorizontalDown")
        self.LineVerticalRight = QtWidgets.QFrame(self.centralwidget)
        self.LineVerticalRight.setGeometry(QtCore.QRect(540, 90, 16, 121))
        self.LineVerticalRight.setFrameShape(QtWidgets.QFrame.VLine)
        self.LineVerticalRight.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineVerticalRight.setObjectName("LineVerticalRight")
        self.AddressText = QtWidgets.QLineEdit(self.centralwidget)
        self.AddressText.setGeometry(QtCore.QRect(330, 110, 191, 21))
        self.AddressText.setObjectName("AddressText")
        self.PortLabel = QtWidgets.QLabel(self.centralwidget)
        self.PortLabel.setGeometry(QtCore.QRect(220, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PortLabel.setFont(font)
        self.PortLabel.setObjectName("PortLabel")
        self.PortText = QtWidgets.QLineEdit(self.centralwidget)
        self.PortText.setGeometry(QtCore.QRect(330, 140, 191, 21))
        self.PortText.setObjectName("PortText")
        self.TestBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TestBtn.setGeometry(QtCore.QRect(380, 170, 81, 41))
        self.TestBtn.setObjectName("TestBtn")
        self.LineHorizontalDown_2 = QtWidgets.QFrame(self.centralwidget)
        self.LineHorizontalDown_2.setGeometry(QtCore.QRect(200, 70, 351, 41))
        self.LineHorizontalDown_2.setAutoFillBackground(False)
        self.LineHorizontalDown_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.LineHorizontalDown_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineHorizontalDown_2.setObjectName("LineHorizontalDown_2")
        self.RecognizeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RecognizeBtn.setGeometry(QtCore.QRect(460, 170, 81, 41))
        self.RecognizeBtn.setObjectName("RecognizeBtn")
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel.setGeometry(QtCore.QRect(220, 180, 161, 16))
        self.StatusLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.StatusLabel.setObjectName("StatusLabel")
        self.OuchiLabel = QtWidgets.QLabel(self.centralwidget)
        self.OuchiLabel.setGeometry(QtCore.QRect(460, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.OuchiLabel.setFont(font)
        self.OuchiLabel.setObjectName("OuchiLabel")
        self.OuchiText = QtWidgets.QLineEdit(self.centralwidget)
        self.OuchiText.setGeometry(QtCore.QRect(510, 440, 211, 21))
        self.OuchiText.setObjectName("OuchiText")
        self.ProcessBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ProcessBtn.setGeometry(QtCore.QRect(30, 480, 113, 41))
        self.ProcessBtn.setObjectName("ProcessBtn")
        self.HistoryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.HistoryBtn.setGeometry(QtCore.QRect(160, 480, 113, 41))
        self.HistoryBtn.setObjectName("HistoryBtn")
        self.VideoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.VideoBtn.setGeometry(QtCore.QRect(290, 480, 113, 41))
        self.VideoBtn.setObjectName("VideoBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLabel.setText(_translate("MainWindow", "身份证信息识别系统"))
        self.ChooseFileBtn.setText(_translate("MainWindow", "选择文件"))
        self.ResultLabel.setText(_translate("MainWindow", "识别结果"))
        self.NameLabel.setText(_translate("MainWindow", "姓名"))
        self.SexLabel.setText(_translate("MainWindow", "性别"))
        self.NationLabel.setText(_translate("MainWindow", "民族"))
        self.NumberLabel.setText(_translate("MainWindow", "身份证号"))
        self.AddressLabel.setText(_translate("MainWindow", "识别服务器地址"))
        self.PortLabel.setText(_translate("MainWindow", "识别服务器端口"))
        self.TestBtn.setText(_translate("MainWindow", "测试连接"))
        self.RecognizeBtn.setText(_translate("MainWindow", "开始识别"))
        self.StatusLabel.setText(_translate("MainWindow", "未连接上"))
        self.OuchiLabel.setText(_translate("MainWindow", "地址"))
        self.ProcessBtn.setText(_translate("MainWindow", "处理图片"))
        self.HistoryBtn.setText(_translate("MainWindow", "历史记录"))
        self.VideoBtn.setText(_translate("MainWindow", "视频抓脸"))
